# docker-compose.yml 

version: '3.8'

services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    networks:
      - app_network

  dashboard:
    build: ./dashboard
    container_name: dashboard_container
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge